/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomFixedBar: typeof import('../components/BottomFixedBar.vue')['default']
    FooterInfo: typeof import('../components/FooterInfo.vue')['default']
    GameSwiper: typeof import('../components/GameSwiper.vue')['default']
    IndexReservationForm: typeof import('../components/IndexReservationForm.vue')['default']
    PrizeListPopup: typeof import('../components/PrizeListPopup.vue')['default']
    ReservationForm: typeof import('../components/ReservationForm.vue')['default']
    ReservationPopups: typeof import('../components/ReservationPopups.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('../components/TabBar.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
